- name: install nginx
  yum: name=nginx state=present

- name: Configure nginx.conf
  template:
    src: ssp.conf.j2
    dest: "{{ nginx_config_path }}/conf.d/{{ item }}"
    mode: 0644
  with_items: "{{ nginx_site_filenames }}"

#- name: Enabled the nginx service
#  service: name=nginx state=started enabled=yes
#
#- name: install firewalld
#  yum: name=firewalld state=present
#
#- name: Start firewalld
#  service: name=firewalld state=started enabled=yes
#
#- name: allow http traffic
#  firewalld: service=http permanent=true state=enabled
#
#- name: reload firewalld
#  command: firewall-cmd --reload
